const http = require('http');

const server = http.createServer((req, res)=>{
    
    console.log("Log generated by Index File from Node App");
    res.write("Welcome to NODE app!");
    res.end(); 

}   );

//server.listen(process.env.PORT);
server.listen(3000);

/*
Environment = Resources
-------------

OS (Linux)
NodeJS (Software/CLI)
Port (3000)
index.js

Command Terminal
-------------
node index.js

*/